M48
; DRILL file KiCad 10.0.3 date 2026-08-10T15:45:15
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-10T15:45:15+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X80.249Y-62.888
T2
X35.0Y-20.0
X35.0Y-74.5
X89.5Y-20.5
X89.5Y-74.5
T1
G00X80.249Y-55.838
M15
G01X80.249Y-55.538
M16
G05
M30
